---
# List handlers for Apache2

- name: Restart apache
  service: name=apache2 state=restarted

- name: Graceful apache
  service: name=apache2 state=graceful

- name: Start mariadb
  service: name=mysql state=started

- name: Stop mariadb
  service: name=mysql state=stoped

- name: Restart mariadb
  service: name=mysql state=restarted